---
title: "class activity 3"
author: "Charles Lang"
date: "10/2/2018"
output: html_document
---

```{r}
#install.packages("ggplot2")
library(tidyverse)
```

#Mapping aesthetic to data to = layer
```{r}
ggplot(diamonds, aes(x = price, y = carat)) +
  geom_point()
```

#Two layers
```{r}
ggplot(mpg, aes(reorder(class, hwy), hwy)) +
  geom_jitter() +
  geom_boxplot()
```

```{r}

#Plot count
ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(y = ..count..), binwidth=0.2) +
  facet_wrap(~ cut) + xlim(50, 70)

#Plot density
ggplot(diamonds, aes(depth)) +
  geom_histogram(aes(y = ..density..), binwidth=0.2) +
  facet_wrap(~ cut) + xlim(50, 70)
```

```{r}
ggplot(mpg, aes(displ, hwy, color = class)) +
  geom_point()

```

Can you create a line graph using the "economics_long" data set that shows change over time in "value01" for different categories of "variable"?

```{r}
economics_long %>% 
  ggplot(aes(x = date, y= value01)) + 
  geom_line() + 
  facet_wrap(~variable)
```

If you would like to recreate the Minard graphic of Napoleon's Troops the code is below and the data is in this repo.

```{r}
cities <- read_table2(file = "cities.txt")
troops <- read_table2(file = "troops.txt")
temps <- read_table2(file = "temps.txt")
```


```{r}
ggplot(cities, aes(long, lat)) +
      geom_path(data = troops, aes(size = survivors,
                    colour = direction,
                    group = interaction(group, direction))) +
      geom_text(aes(label = city),
                hjust = 0,
                vjust = 1,
                size = 4)

# Polish appearance
last_plot() +
  scale_x_continuous("", limits = c(24, 39)) +
  scale_y_continuous("") +
  scale_colour_manual(values = c("grey50","red")) +
  scale_size(range = c(1, 10))
```

